// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWL6qUT_zcc0SzFSEBHXEmncGyt0kF8ZM',
    appId: '1:936404473683:web:3033d3da864efb9df1b3a6',
    messagingSenderId: '936404473683',
    projectId: 'chat-reactjs-99a6d',
    authDomain: 'chat-reactjs-99a6d.firebaseapp.com',
    storageBucket: 'chat-reactjs-99a6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqI0iVZOxY3mOEVeJzivunkhXD38p_YE',
    appId: '1:936404473683:android:cb4587bd44513d57f1b3a6',
    messagingSenderId: '936404473683',
    projectId: 'chat-reactjs-99a6d',
    storageBucket: 'chat-reactjs-99a6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI4-N1JH8YR5oGAZ870J4Bu3bnJ_p3L8U',
    appId: '1:936404473683:ios:e6e5e1d8ea4c4f98f1b3a6',
    messagingSenderId: '936404473683',
    projectId: 'chat-reactjs-99a6d',
    storageBucket: 'chat-reactjs-99a6d.appspot.com',
    iosClientId: '936404473683-9cnd3eqn55hhl4rkrclredcs3gbdb5in.apps.googleusercontent.com',
    iosBundleId: 'com.example.summercamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI4-N1JH8YR5oGAZ870J4Bu3bnJ_p3L8U',
    appId: '1:936404473683:ios:e6e5e1d8ea4c4f98f1b3a6',
    messagingSenderId: '936404473683',
    projectId: 'chat-reactjs-99a6d',
    storageBucket: 'chat-reactjs-99a6d.appspot.com',
    iosClientId: '936404473683-9cnd3eqn55hhl4rkrclredcs3gbdb5in.apps.googleusercontent.com',
    iosBundleId: 'com.example.summercamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbV0LFddTxSY1ItNFWadnWF34IFdpNyjE',
    appId: '1:936404473683:web:a9320663d0a1c6bcf1b3a6',
    messagingSenderId: '936404473683',
    projectId: 'chat-reactjs-99a6d',
    authDomain: 'chat-reactjs-99a6d.firebaseapp.com',
    storageBucket: 'chat-reactjs-99a6d.appspot.com',
  );
}
